
/**
 * @file inthandler.c
 * @author Pseudo-Kernel (sandbox.isolated@gmail.com)
 * @brief Implements interrupt handlers.
 * @version 0.1
 * @date 2021-10-24
 * 
 * @copyright Copyright (c) 2021
 * 
 */

#include <base/base.h>
#include <ke/lock.h>
#include <ke/keinit.h>
#include <ke/interrupt.h>
#include <ke/kprocessor.h>
#include <ke/inthandler.h>
#include <mm/mm.h>
#include <mm/pool.h>
#include <init/bootgfx.h>
#include <hal/acpi.h>
#include <hal/apic.h>
#include <ke/thread.h>

// forward reference.
VOID
KiYieldThreadInternal(
    IN KSTACK_FRAME_INTERRUPT *InterruptFrame);


PTR KiInterruptHandlers[0x100] =
{
    (PTR)&KiDivideFault,
    (PTR)&KiDebugTrap,
    (PTR)&KiNMIInterrupt,
    (PTR)&KiBreakpointTrap,
    (PTR)&KiOverflowTrap,
    (PTR)&KiBoundFault,
    (PTR)&KiInvalidOpcode,
    (PTR)&KiCoprocessorNotAvailable,
    (PTR)&KiDoubleFault,
    (PTR)&KiCoprocessorSegmentOverrun,
    (PTR)&KiInvalidTss,
    (PTR)&KiSegmentNotPresent,
    (PTR)&KiStackSegmentFault,
    (PTR)&KiGeneralProtectionFault,
    (PTR)&KiPageFault,
    (PTR)&KiUnexpectedException15,
    (PTR)&KiX87FloatingPointFault,
    (PTR)&KiAlignmentFault,
    (PTR)&KiMachineCheck,
    (PTR)&KiSIMDFloatingPointFault,
    (PTR)&KiVirtualizationFault,
    (PTR)&KiControlProtectionFault,

    (PTR)&KiUnexpectedException22,
    (PTR)&KiUnexpectedException23,
    (PTR)&KiUnexpectedException24,
    (PTR)&KiUnexpectedException25,
    (PTR)&KiUnexpectedException26,
    (PTR)&KiUnexpectedException27,
    (PTR)&KiUnexpectedException28,
    (PTR)&KiUnexpectedException29,
    (PTR)&KiUnexpectedException30,
    (PTR)&KiUnexpectedException31,

    (PTR)&KiYieldThreadInterrupt, // Software interrupt which yields current thread

    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(33), // Reserved by kernel
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(34), // Reserved by kernel
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(35), // Reserved by kernel
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(36), // Reserved by kernel
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(37), // Reserved by kernel
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(38), // Reserved by kernel
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(39), // Reserved by kernel
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(40), // Reserved by kernel
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(41), // Reserved by kernel
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(42), // Reserved by kernel
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(43), // Reserved by kernel
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(44), // Reserved by kernel
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(45), // Reserved by kernel
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(46), // Reserved by kernel
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(47), // Reserved by kernel

    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(48),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(49),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(50),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(51),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(52),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(53),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(54),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(55),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(56),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(57),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(58),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(59),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(60),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(61),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(62),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(63),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(64),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(65),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(66),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(67),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(68),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(69),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(70),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(71),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(72),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(73),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(74),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(75),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(76),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(77),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(78),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(79),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(80),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(81),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(82),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(83),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(84),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(85),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(86),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(87),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(88),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(89),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(90),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(91),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(92),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(93),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(94),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(95),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(96),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(97),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(98),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(99),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(100),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(101),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(102),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(103),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(104),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(105),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(106),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(107),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(108),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(109),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(110),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(111),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(112),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(113),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(114),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(115),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(116),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(117),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(118),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(119),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(120),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(121),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(122),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(123),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(124),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(125),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(126),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(127),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(128),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(129),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(130),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(131),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(132),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(133),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(134),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(135),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(136),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(137),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(138),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(139),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(140),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(141),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(142),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(143),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(144),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(145),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(146),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(147),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(148),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(149),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(150),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(151),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(152),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(153),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(154),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(155),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(156),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(157),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(158),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(159),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(160),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(161),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(162),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(163),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(164),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(165),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(166),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(167),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(168),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(169),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(170),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(171),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(172),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(173),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(174),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(175),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(176),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(177),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(178),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(179),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(180),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(181),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(182),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(183),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(184),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(185),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(186),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(187),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(188),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(189),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(190),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(191),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(192),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(193),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(194),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(195),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(196),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(197),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(198),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(199),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(200),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(201),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(202),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(203),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(204),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(205),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(206),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(207),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(208),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(209),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(210),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(211),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(212),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(213),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(214),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(215),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(216),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(217),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(218),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(219),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(220),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(221),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(222),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(223),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(224),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(225),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(226),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(227),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(228),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(229),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(230),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(231),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(232),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(233),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(234),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(235),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(236),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(237),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(238),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(239),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(240),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(241),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(242),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(243),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(244),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(245),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(246),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(247),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(248),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(249),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(250),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(251),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(252),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(253),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(254),
    (PTR)&INTERRUPT_HANDLER_NAME_BY_VECTOR(255),
};


EXCEPTION_HANDLER_PUSH_ERRCODE(KiDivideFault, 0)
EXCEPTION_HANDLER_PUSH_ERRCODE(KiDebugTrap, 1)
EXCEPTION_HANDLER_PUSH_ERRCODE(KiNMIInterrupt, 2)
EXCEPTION_HANDLER_PUSH_ERRCODE(KiBreakpointTrap, 3)
EXCEPTION_HANDLER_PUSH_ERRCODE(KiOverflowTrap, 4)
EXCEPTION_HANDLER_PUSH_ERRCODE(KiBoundFault, 5)
EXCEPTION_HANDLER_PUSH_ERRCODE(KiInvalidOpcode, 6)
EXCEPTION_HANDLER_PUSH_ERRCODE(KiCoprocessorNotAvailable, 7)
EXCEPTION_HANDLER(KiDoubleFault, 8)
EXCEPTION_HANDLER_PUSH_ERRCODE(KiCoprocessorSegmentOverrun, 9)
EXCEPTION_HANDLER(KiInvalidTss, 10)
EXCEPTION_HANDLER(KiSegmentNotPresent, 11)
EXCEPTION_HANDLER(KiStackSegmentFault, 12)
EXCEPTION_HANDLER(KiGeneralProtectionFault, 13)
EXCEPTION_HANDLER(KiPageFault, 14)
EXCEPTION_HANDLER_PUSH_ERRCODE(KiUnexpectedException15, 15) //Reserved by intel
EXCEPTION_HANDLER_PUSH_ERRCODE(KiX87FloatingPointFault, 16)
EXCEPTION_HANDLER(KiAlignmentFault, 17)
EXCEPTION_HANDLER_PUSH_ERRCODE(KiMachineCheck, 18)
EXCEPTION_HANDLER_PUSH_ERRCODE(KiSIMDFloatingPointFault, 19)
EXCEPTION_HANDLER_PUSH_ERRCODE(KiVirtualizationFault, 20)
EXCEPTION_HANDLER(KiControlProtectionFault, 21)

EXCEPTION_HANDLER(KiUnexpectedException22, 22) //Reserved by intel
EXCEPTION_HANDLER(KiUnexpectedException23, 23) //Reserved by intel
EXCEPTION_HANDLER(KiUnexpectedException24, 24) //Reserved by intel
EXCEPTION_HANDLER(KiUnexpectedException25, 25) //Reserved by intel
EXCEPTION_HANDLER(KiUnexpectedException26, 26) //Reserved by intel
EXCEPTION_HANDLER(KiUnexpectedException27, 27) //Reserved by intel
EXCEPTION_HANDLER(KiUnexpectedException28, 28) //Reserved by intel
EXCEPTION_HANDLER(KiUnexpectedException29, 29) //Reserved by intel
EXCEPTION_HANDLER(KiUnexpectedException30, 30) //Reserved by intel
EXCEPTION_HANDLER(KiUnexpectedException31, 31) //Reserved by intel


INTERRUPT_HANDLER_SOFTWARE(KiYieldThreadInterrupt, KiYieldThreadInternal)
INTERRUPT_HANDLER(32) //Reserved by kernel
INTERRUPT_HANDLER(33) //Reserved by kernel
INTERRUPT_HANDLER(34) //Reserved by kernel
INTERRUPT_HANDLER(35) //Reserved by kernel
INTERRUPT_HANDLER(36) //Reserved by kernel
INTERRUPT_HANDLER(37) //Reserved by kernel
INTERRUPT_HANDLER(38) //Reserved by kernel
INTERRUPT_HANDLER(39) //Reserved by kernel
INTERRUPT_HANDLER(40) //Reserved by kernel
INTERRUPT_HANDLER(41) //Reserved by kernel
INTERRUPT_HANDLER(42) //Reserved by kernel
INTERRUPT_HANDLER(43) //Reserved by kernel
INTERRUPT_HANDLER(44) //Reserved by kernel
INTERRUPT_HANDLER(45) //Reserved by kernel
INTERRUPT_HANDLER(46) //Reserved by kernel
INTERRUPT_HANDLER(47) //Reserved by kernel

INTERRUPT_HANDLER(48)
INTERRUPT_HANDLER(49)
INTERRUPT_HANDLER(50)
INTERRUPT_HANDLER(51)
INTERRUPT_HANDLER(52)
INTERRUPT_HANDLER(53)
INTERRUPT_HANDLER(54)
INTERRUPT_HANDLER(55)
INTERRUPT_HANDLER(56)
INTERRUPT_HANDLER(57)
INTERRUPT_HANDLER(58)
INTERRUPT_HANDLER(59)
INTERRUPT_HANDLER(60)
INTERRUPT_HANDLER(61)
INTERRUPT_HANDLER(62)
INTERRUPT_HANDLER(63)
INTERRUPT_HANDLER(64)
INTERRUPT_HANDLER(65)
INTERRUPT_HANDLER(66)
INTERRUPT_HANDLER(67)
INTERRUPT_HANDLER(68)
INTERRUPT_HANDLER(69)
INTERRUPT_HANDLER(70)
INTERRUPT_HANDLER(71)
INTERRUPT_HANDLER(72)
INTERRUPT_HANDLER(73)
INTERRUPT_HANDLER(74)
INTERRUPT_HANDLER(75)
INTERRUPT_HANDLER(76)
INTERRUPT_HANDLER(77)
INTERRUPT_HANDLER(78)
INTERRUPT_HANDLER(79)
INTERRUPT_HANDLER(80)
INTERRUPT_HANDLER(81)
INTERRUPT_HANDLER(82)
INTERRUPT_HANDLER(83)
INTERRUPT_HANDLER(84)
INTERRUPT_HANDLER(85)
INTERRUPT_HANDLER(86)
INTERRUPT_HANDLER(87)
INTERRUPT_HANDLER(88)
INTERRUPT_HANDLER(89)
INTERRUPT_HANDLER(90)
INTERRUPT_HANDLER(91)
INTERRUPT_HANDLER(92)
INTERRUPT_HANDLER(93)
INTERRUPT_HANDLER(94)
INTERRUPT_HANDLER(95)
INTERRUPT_HANDLER(96)
INTERRUPT_HANDLER(97)
INTERRUPT_HANDLER(98)
INTERRUPT_HANDLER(99)
INTERRUPT_HANDLER(100)
INTERRUPT_HANDLER(101)
INTERRUPT_HANDLER(102)
INTERRUPT_HANDLER(103)
INTERRUPT_HANDLER(104)
INTERRUPT_HANDLER(105)
INTERRUPT_HANDLER(106)
INTERRUPT_HANDLER(107)
INTERRUPT_HANDLER(108)
INTERRUPT_HANDLER(109)
INTERRUPT_HANDLER(110)
INTERRUPT_HANDLER(111)
INTERRUPT_HANDLER(112)
INTERRUPT_HANDLER(113)
INTERRUPT_HANDLER(114)
INTERRUPT_HANDLER(115)
INTERRUPT_HANDLER(116)
INTERRUPT_HANDLER(117)
INTERRUPT_HANDLER(118)
INTERRUPT_HANDLER(119)
INTERRUPT_HANDLER(120)
INTERRUPT_HANDLER(121)
INTERRUPT_HANDLER(122)
INTERRUPT_HANDLER(123)
INTERRUPT_HANDLER(124)
INTERRUPT_HANDLER(125)
INTERRUPT_HANDLER(126)
INTERRUPT_HANDLER(127)
INTERRUPT_HANDLER(128)
INTERRUPT_HANDLER(129)
INTERRUPT_HANDLER(130)
INTERRUPT_HANDLER(131)
INTERRUPT_HANDLER(132)
INTERRUPT_HANDLER(133)
INTERRUPT_HANDLER(134)
INTERRUPT_HANDLER(135)
INTERRUPT_HANDLER(136)
INTERRUPT_HANDLER(137)
INTERRUPT_HANDLER(138)
INTERRUPT_HANDLER(139)
INTERRUPT_HANDLER(140)
INTERRUPT_HANDLER(141)
INTERRUPT_HANDLER(142)
INTERRUPT_HANDLER(143)
INTERRUPT_HANDLER(144)
INTERRUPT_HANDLER(145)
INTERRUPT_HANDLER(146)
INTERRUPT_HANDLER(147)
INTERRUPT_HANDLER(148)
INTERRUPT_HANDLER(149)
INTERRUPT_HANDLER(150)
INTERRUPT_HANDLER(151)
INTERRUPT_HANDLER(152)
INTERRUPT_HANDLER(153)
INTERRUPT_HANDLER(154)
INTERRUPT_HANDLER(155)
INTERRUPT_HANDLER(156)
INTERRUPT_HANDLER(157)
INTERRUPT_HANDLER(158)
INTERRUPT_HANDLER(159)
INTERRUPT_HANDLER(160)
INTERRUPT_HANDLER(161)
INTERRUPT_HANDLER(162)
INTERRUPT_HANDLER(163)
INTERRUPT_HANDLER(164)
INTERRUPT_HANDLER(165)
INTERRUPT_HANDLER(166)
INTERRUPT_HANDLER(167)
INTERRUPT_HANDLER(168)
INTERRUPT_HANDLER(169)
INTERRUPT_HANDLER(170)
INTERRUPT_HANDLER(171)
INTERRUPT_HANDLER(172)
INTERRUPT_HANDLER(173)
INTERRUPT_HANDLER(174)
INTERRUPT_HANDLER(175)
INTERRUPT_HANDLER(176)
INTERRUPT_HANDLER(177)
INTERRUPT_HANDLER(178)
INTERRUPT_HANDLER(179)
INTERRUPT_HANDLER(180)
INTERRUPT_HANDLER(181)
INTERRUPT_HANDLER(182)
INTERRUPT_HANDLER(183)
INTERRUPT_HANDLER(184)
INTERRUPT_HANDLER(185)
INTERRUPT_HANDLER(186)
INTERRUPT_HANDLER(187)
INTERRUPT_HANDLER(188)
INTERRUPT_HANDLER(189)
INTERRUPT_HANDLER(190)
INTERRUPT_HANDLER(191)
INTERRUPT_HANDLER(192)
INTERRUPT_HANDLER(193)
INTERRUPT_HANDLER(194)
INTERRUPT_HANDLER(195)
INTERRUPT_HANDLER(196)
INTERRUPT_HANDLER(197)
INTERRUPT_HANDLER(198)
INTERRUPT_HANDLER(199)
INTERRUPT_HANDLER(200)
INTERRUPT_HANDLER(201)
INTERRUPT_HANDLER(202)
INTERRUPT_HANDLER(203)
INTERRUPT_HANDLER(204)
INTERRUPT_HANDLER(205)
INTERRUPT_HANDLER(206)
INTERRUPT_HANDLER(207)
INTERRUPT_HANDLER(208)
INTERRUPT_HANDLER(209)
INTERRUPT_HANDLER(210)
INTERRUPT_HANDLER(211)
INTERRUPT_HANDLER(212)
INTERRUPT_HANDLER(213)
INTERRUPT_HANDLER(214)
INTERRUPT_HANDLER(215)
INTERRUPT_HANDLER(216)
INTERRUPT_HANDLER(217)
INTERRUPT_HANDLER(218)
INTERRUPT_HANDLER(219)
INTERRUPT_HANDLER(220)
INTERRUPT_HANDLER(221)
INTERRUPT_HANDLER(222)
INTERRUPT_HANDLER(223)
INTERRUPT_HANDLER(224)
INTERRUPT_HANDLER(225)
INTERRUPT_HANDLER(226)
INTERRUPT_HANDLER(227)
INTERRUPT_HANDLER(228)
INTERRUPT_HANDLER(229)
INTERRUPT_HANDLER(230)
INTERRUPT_HANDLER(231)
INTERRUPT_HANDLER(232)
INTERRUPT_HANDLER(233)
INTERRUPT_HANDLER(234)
INTERRUPT_HANDLER(235)
INTERRUPT_HANDLER(236)
INTERRUPT_HANDLER(237)
INTERRUPT_HANDLER(238)
INTERRUPT_HANDLER(239)
INTERRUPT_HANDLER(240)
INTERRUPT_HANDLER(241)
INTERRUPT_HANDLER(242)
INTERRUPT_HANDLER(243)
INTERRUPT_HANDLER(244)
INTERRUPT_HANDLER(245)
INTERRUPT_HANDLER(246)
INTERRUPT_HANDLER(247)
INTERRUPT_HANDLER(248)
INTERRUPT_HANDLER(249)
INTERRUPT_HANDLER(250)
INTERRUPT_HANDLER(251)
INTERRUPT_HANDLER(252)
INTERRUPT_HANDLER(253)
INTERRUPT_HANDLER(254)
INTERRUPT_HANDLER(255)



VOID
KERNELAPI
KiDispatchException(
    IN U32 ExceptionId,
    IN KSTACK_FRAME_INTERRUPT *Frame)
{
    if (ExceptionId == 7)
    {
        // Ensure that interrupt is disabled when handling #NM
        DASSERT(!(__readeflags() & RFLAG_IF));

        // Clear CR0.TS before execute fxrstor64 as it raises #NM
        __writecr0(__readcr0() & ~ARCH_X64_CR0_TS);

        // Restore the SSE state.
        KTHREAD *Thread = KeGetCurrentThread();
        _fxrstor64(&Thread->ThreadContext.FXSTATE);
        return;
    }

    FATAL(
        " ********** Exception (ID %d, Frame 0x%016llx) **********\n"
        "RAX = 0x%016llx, RBX = 0x%016llx, RCX = 0x%016llx, RDX = 0x%016llx, \n"
        "RSI = 0x%016llx, RDI = 0x%016llx, RBP = 0x%016llx, R8  = 0x%016llx, \n"
        "R9  = 0x%016llx, R10 = 0x%016llx, R11 = 0x%016llx, R12 = 0x%016llx, \n"
        "R13 = 0x%016llx, R14 = 0x%016llx, R15 = 0x%016llx, \n"
        "CS:RIP = 0x%04hx:0x%016llx, SS:RSP = 0x%04hx:0x%016llx, RFLAGS = 0x%016llx, \n"
        "DS = 0x%04hx, ES = 0x%04hx, FS = 0x%04hx, GS = 0x%04hx, \n"
        "CR0 = 0x%016llx, CR2 = 0x%016llx, CR3 = 0x%016llx, CR4 = 0x%016llx, \n"
        "CR8 = 0x%016llx, ErrorCode = 0x%016llx\n",
        ExceptionId, Frame,
        Frame->Rax, Frame->Rbx, Frame->Rcx, Frame->Rdx, 
        Frame->Rsi, Frame->Rdi, Frame->Rbp, Frame->R8,
        Frame->R9, Frame->R10, Frame->R11, Frame->R12,
        Frame->R13, Frame->R14, Frame->R15,
        Frame->Cs, Frame->Rip, Frame->Ss, Frame->Rsp, Frame->Rflags,
        Frame->Ds, Frame->Es, Frame->Fs, Frame->Gs,
        __readcr0(), __readcr2(), __readcr3(), __readcr4(),
        __readcr8(), Frame->ErrorCode
    );

    _disable();
    __halt();
}

